# Generated by Django 5.1.5 on 2025-01-19 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_salesitem_dosage_form_wholesalesalesitem_dosage_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensinglog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='itemselectionhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='wholesalereceipt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='wholesaleselectionhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
