# Generated by Django 5.1.5 on 2025-01-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_dispensinglog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensinglog',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
