# Generated by Django 5.1.5 on 2025-01-20 06:50

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_dispensinglog_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=50, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='wholesalereceipt',
            name='receipt_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=50, prefix='', unique=True),
        ),
    ]
