# Generated by Django 5.1.5 on 2025-01-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_receipt_receipt_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='printed',
        ),
        migrations.RemoveField(
            model_name='wholesalereceipt',
            name='printed',
        ),
    ]
