# Generated by Django 5.1.5 on 2025-01-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
