# Generated by Django 5.1.5 on 2025-01-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_cart_item_wholesalecart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleitem',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
