# Generated by Django 5.1.5 on 2025-01-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_cart_item_wholesalecart'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementitem',
            name='dosage_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.formulation'),
        ),
        migrations.AddField(
            model_name='wholesaleprocurementitem',
            name='dosage_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.formulation'),
        ),
    ]
