# Generated by Django 5.1.5 on 2025-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Pharmacist', 'Pharmacist'), ('Pharm-Tech', 'Pharm-Tech')], max_length=200, null=True),
        ),
    ]
