# Generated by Django 5.1.5 on 2025-01-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_profile_image_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='undraw_profile.svg', null=True, upload_to='uploads/images/'),
        ),
    ]
